### ISSUE TITLE
Enhancement: Custom CSPROJ

### ISSUE THREAD

**Issue by AndrewDRX** [RobertBorghese/reflaxe.CSharp#10]
## Request ##

Add a `Define` to allow for specifying a custom csproj file.

## Suggested Syntax ##

The syntax could be as follows:
```hxml
-D csproj=path/to/file.csproj
```

## Details ##

Currently, the build.csproj file is autogenerated.

There is currently the following `Define` to specify that the generation of the csproj should be skipped:
```hxml
-D no-csproj
```

A custom csproj can still currently be used by disabling the auto generated version as mentioned above, and then writing a macro to copy a custom version to the output directory; however, it would be much more convenient to have the option to instead let the compiler handle the copying of the user-specified csproj.

## Suggested Code Change ##

I can submit a pull request to show a rough idea of what this would look like.

## Additional Thoughts ##

This sort of ties into another issue where the deprecated haxe `--cs` target also generated all of the C# output for the haxe standard library, whereas this new reflaxe target does not.

I actually see this as an improvement to a degree since generating all of the haxe standard libraries will cause namespacing conflicts/errors in the event that a project tries to include multiple haxe-generated libraries that both defined the same haxe namespace.

By using a custom csproj, it allows someone to deploy the haxe standard library as a separate nuget C# package, and then any other haxe project can just include a csproj file that references that shared haxe standard library nuget package (rather than trying to regenerate the standard library into each project).

And if there ever is a nuget package for the haxe standard library, then perhaps the default csproj generated by this reflaxe target can also be updated to always include that (or optionally include that w/ a new flag).

**Comment by jeremyfa** [comment]
I guess `csproj=` could be slightly more convenient yes. And yes, it could help with more specific cases where you want to share the same standard lib for multiple projects. Sounds good to me.

**Comment by jeremyfa** [comment]
Regarding the standard library, we didn't tackle that subject yet. This is something I'll start digging into in the coming weeks

**Comment by AndrewDRX** [comment]
> Regarding the standard library, we didn't tackle that subject yet. This is something I'll start digging into in the coming weeks

Excellent! Glad to see something is in the works for that. I did realize that how it is currently (class access modifier as unspecified, defaulting to `internal`) probably won't cause any namespace conflicts/errors, so not the worst case if every project includes an internal-access copy of the standard library. Just a bit of extra bloat.
