### ISSUE TITLE
Replacement

### ISSUE THREAD

**Issue by hoseyjoe** [RobertBorghese/reflaxe.CSharp#6]
I read that C# may be dropped as target in haxe5. Is this likely to be a resolution to that? How solid is it today vs current C#?

Also any thoughts if this will resolve?  
https://github.com/HaxeFoundation/haxe/issues/4872

We use issue #1 auto externs so I could not test this.

**Comment by jeremyfa** [comment]
This repository is under active development, quite far from being usable as it was started just a few weeks ago and there is a lot to do, but yeah, the idea is to have a good C# target replacement for Haxe eventually, before the original one gets discarded some day.

And afaik there is nothing decided and set in the stone by haxe team about removing C# target in haxe 5 for sure, but I guess this will also depends on how well this alternative implementation gets completed meanwhile.

The issue you referenced looks like a good reference we should keep around when implementing Array stuff!

**Comment by hoseyjoe** [comment]
Great! Thank you for the comment.
